### ISSUE TITLE
README.md has dead links

### ISSUE THREAD

**Issue by wad209** [ndmitchell/hoogle#111]
This is just a small issue, but in README.md, under Hoogle Use, the following two bullet points have dead URLs:
* **[Installed locally](https://github.com/ndmitchell/hoogle/blob/master/docs/Local-Install.md)**, with either a command line or in a browser
* **[As a developer](https://github.com/ndmitchell/hoogle/blob/master/docs/Developers.md)**, through Haskell or JSON APIs.

**Comment by ndmitchell** [comment]
Thanks, I've fixed them. The content on all three pages is still incorrect/evolving, but might as well link to the right place.

**Comment by wad209** [comment]
No problem, thanks for this great project!

**Comment by wolftune** [comment]
so shouldn't this ticket be closed if fixed?

**Comment by ndmitchell** [comment]
Yes, it should. I've been fairly lax about closing tickets during the 4 to 5 conversion, since most things are fixed in at most one version. But for the website, this is just fixed :)
