### ISSUE TITLE
Bottom search results are truncated.

### ISSUE THREAD

**Issue by Cipherwraith** [ndmitchell/hoogle#112]
I havent investigated the cause, but I assume it is caused by the css overflow property not being set correctly.

![screen shot 2015-05-05 at 11 36 06 pm](https://cloud.githubusercontent.com/assets/5457807/7476360/a23d1796-f37f-11e4-81ae-bac0c3da41a2.png)

**Comment by ndmitchell** [comment]
Yep, I saw that too. If you can suggest the right magic CSS to fix it I'd be grateful (and a pull request would be even better!).

**Comment by Cipherwraith** [comment]
Sure thing, ill modify the CSS and submit a pull request.

**Comment by Cipherwraith** [comment]
I have made a pull request for this issue here:
https://github.com/ndmitchell/hoogle/pull/114
