### ISSUE TITLE
Do something clever with the new `@since` annotation

### ISSUE THREAD

**Issue by hvr** [ndmitchell/hoogle#117]
Since GHC 7.10/haddock-2.16, Haddock has a new markup for `@since`-annotations.

It's used throughout `base`, e.g.

```haskell
-- | An infix synonym for 'mappend'.
--
-- @since 4.5.0.0
(<>) :: Monoid m => m -> m -> m
(<>) = mappend
```

I wonder if Hoogle could somehow pick that annotation up and do something interesting with it...

**Comment by ndmitchell** [comment]
Any ideas as to what? Generally, excluding newer functions is probably a bad idea.

**Comment by ndmitchell** [comment]
I guess one "clever" thing for base would be to mark it up as "since GHC 7.8" instead of "since 4.5.0.0" (which is basically meaningless to most people). Not sure if Haddock should be doing that instead though.

**Comment by ndmitchell** [comment]
Can't think of anything clever to do, so not doing anything.
