### ISSUE TITLE
Bug tracker link on haskell.org/hoogle points to Google Code, not GitHub

### ISSUE THREAD

**Issue by ntc2** [ndmitchell/hoogle#140]
The "bug tracker" link points to `http://code.google.com/p/ndmitchell/issues/list` but it should point to `https://github.com/ndmitchell/hoogle/issues` instead.

**Comment by ndmitchell** [comment]
Also fixed at http://hoogle.haskell.org/, although I actually don't have a bug tracker link there at all - I wonder if it's worth adding?

**Comment by ntc2** [comment]
Looks like you have since added the bug tracker link to http://hoogle.haskell.org -- and yes, I think it was a good idea :)

**Comment by ndmitchell** [comment]
Ah yes, I see it now :)
