### ISSUE TITLE
Data.Monoid.<> missing in search results

### ISSUE THREAD

**Issue by tgerder** [ndmitchell/hoogle#143]
command: hoogle "<>"
or https://www.haskell.org/hoogle/?hoogle=%3C%3E 
Data.Monoid.<> missing

while: hoogle Endo
lists Data.Monoid.Endo
Hoogle v4.2.42

**Comment by ndmitchell** [comment]
It works at the new Hoogle, see http://hoogle.haskell.org/?hoogle=%3C%3E - so requires getting the migration finished.

**Comment by tgerder** [comment]
Excellent! Thanks!
