### ISSUE TITLE
IO UTCTime

### ISSUE THREAD

**Issue by rvion** [ndmitchell/hoogle#144]
on https://www.stackage.org/lts-3.17/hoogle?q=IO+UTCTime , searching `IO UTCTime` doesn't return `getCurrentTime`

__Pics:__

![image](https://cloud.githubusercontent.com/assets/2150990/11633499/eda23d7a-9d0b-11e5-8b3e-94474fe35793.png)

but 

![image](https://cloud.githubusercontent.com/assets/2150990/11633510/ff66370a-9d0b-11e5-80c6-3641295487b3.png)

**Comment by ndmitchell** [comment]
It thinks your search is for the literal words `IO` and `UTCTime`. If you do https://www.stackage.org/lts-3.17/hoogle?q=%3A%3A+IO+UTCTime it works properly, the `::` says "this is a type".

**Comment by rvion** [comment]
my bad, thanks !
