### ISSUE TITLE
Support GHC 8.0

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#148]
Current bottleneck is resourcet, which I've raised at https://github.com/snoyberg/conduit/issues/249

**Comment by ndmitchell** [comment]
And after a few more issues, I'm stuck at https://github.com/jystic/unix-compat/issues/19

**Comment by ndmitchell** [comment]
On Windows, I currently run into https://ghc.haskell.org/trac/ghc/ticket/11552

**Comment by jystic** [comment]
unix-compat should be all sorted now

**Comment by ndmitchell** [comment]
Thanks @jystic!

**Comment by ndmitchell** [comment]
All works now :)
