### ISSUE TITLE
Search is broken with symbols longer than 255 characters

### ISSUE THREAD

**Issue by kuk0** [ndmitchell/hoogle#151]
For a hoogle text file like this (note that the name is longer than 255 chars):

```
module Mod
a :: Int
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb :: Int
d :: Int
```

we can `hoogle dump`, or `hoogle search` by type and get correct results; however, search by name is broken and `hoogle search "d"` returns `No results found`.

I could reproduce this in both hoogle 4 and 5.

This is caused by an overflow in internal representation, where string length is stored in a byte. In hoogle 4, it's:

```
data SubstrSearch a = SubstrSearch
  { text :: Bytestring  -- all the bytestrings, in preference order
  , lens :: Bytestring  -- a list of lengths
  , inds :: Array Int a  -- the results
  }
```

in hoogle 5 it will probably be sth. similar.

I know that names longer than 255 are not very common - still I have recently tripped on this with some autogenerated function names (which were very long). It's ok if we don't try to match the whole string in the super-long name, but it's presence should not affect searching other short names.

Possible fixes:
a) don't include super-long names in the database and throw a warning
b) trim the long names to 255 characters so we don't overflow
c) change the search algorithm to handle long names (i don't really think this is worth it)

**Comment by ndmitchell** [comment]
Nice catch. Truncating to 255 characters before storing in the search database seems best, then people will be able to search for a prefix of the name, and it doesn't impact anything else.

**Comment by ndmitchell** [comment]
Are you sure this is a problem with Hoogle 5? I just tried and couldn't reproduce with a 500 character identifier.

I also searched for all instances of Word8, and only found 2 - one of which I explicitly treated 255+ as 255, and one where I wasn't but do now. Both were in type search so would have been fairly uneventful even if they hadn't been correct.

**Comment by kuk0** [comment]
Err no, false alarm; i can't generate a db for hoogle5 so i surely wasn't reproducing with 5.

**Comment by ndmitchell** [comment]
Yep, to generate a DB for Hoogle5 I had to hack one of the downloaded ones - non-trivial, so I'll try and fix that now :)
