### ISSUE TITLE
Convert active contributor to hoogle5

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#158]
This ticket is for @kuk0 to list all the things they need to do before they convert to Hoogle 5, so the really nice pull requests go into a form I can more readily reuse.

**Comment by ndmitchell** [comment]
From https://github.com/ndmitchell/hoogle/pull/152#issuecomment-187185552 I see:

> We get the text files directly by running haddock --hoogle.
> We have a different build system and don't have cabal integration, so when running hoogle internally, 
> we just convert and combine all the databases. Keeping this low-level api would be nice so that
> hoogle doesn't rely on/assume one particular technology (in this case, cabal).

**Comment by ndmitchell** [comment]
@kuk0 - I've just pushed enough that I think it should be just about usable for you. Using the HEAD version try:

* Put all text files in the same directory, with nothing else in it. e.g. a directory `/hoogle` containing `base.txt` and `mypackage.txt` - one file per package you have.
* Run `hoogle generate --local=/hoogle` which will index them all.
* Run `hoogle server` to start a web server to view them.

My guess is that will work, but you'll need to hack through `hackage` to point them at the Haddock. If so, where are your internal hosted haddock files - do they follow the `/package/name` format?

**Comment by ndmitchell** [comment]
Either contributor converted or is not active anymore - I can't really tell, so closing this ticket.

**Comment by kuk0** [comment]
Hi Neil,
yes, i didn't have time to work on hoogle lately;
but afaict, hoogle5 doesn't have search by type implemented yet, right?
