### ISSUE TITLE
Use hackage dependency count to rank "of a kind" matches

### ISSUE THREAD

**Issue by jwiegley** [ndmitchell/hoogle#16]
If you search for "Map" right now in the current Hoogle (the one in this github repository), `Data.Map` from `containers` will be many places down on the list, because there are many exact matches for the `Map` type and module, and Hoogle lists these exact matches alphabetically.

What I think should happen is that we use Hackage's dependency data to give each hit a ranking based on how widely used the package it's in is.  That is, we count the number of packages in Hackage that depend on every other package, and this number is used to sort like-kinded matches.

With this scheme, "Map" will find `Data.Map` from containers before anything else, simply because containers is used more heavily than all the other packages containing Map as a typename or module name.

**Comment by ndmitchell** [comment]
I now use the popularity rankings of reverse dependencies to order results, see the new code at https://github.com/ndmitchell/hogle/ - in particular https://github.com/ndmitchell/hogle/blob/master/src/Input/Reorder.hs. As expected Map the module and Map the data type are the first two hits at http://hoogle.haskell.org/?hoogle=Map.
