### ISSUE TITLE
query URL to restrict search to package?

### ISSUE THREAD

**Issue by jwaldmann** [ndmitchell/hoogle#162]
Feature request (or doc request - in case feature is already there):

I would love to restrict the search (in the web interface) to a package. Mainly, to base. (Application: my students should use this.)

This type of URL does mention packages: http://haskell.org/hoogle/?hoogle=gtk+%2bpackage but it is looking for packages, not for identifiers inside a package?

This line https://github.com/ndmitchell/hoogle/blob/master/src/Query.hs#L198 indicates that this could work: https://www.haskell.org/hoogle/?hoogle=Bool+package%3Abase but it does not (Parse error: (line 1, column 14): unexpected "b" Bad symbol) 

The error message links to the user manual https://wiki.haskell.org/Hoogle but this has nothing on query URLs.

**Comment by ndmitchell** [comment]
Use Hoogle 5: http://hoogle.haskell.org/?scope=package%3Abase

That has such a feature, and it's very discoverable in the UI, so hopefully doesn't even need documenting.

**Comment by jwaldmann** [comment]
Ah nice.
