### ISSUE TITLE
Incorrect URL for GHC docs

### ISSUE THREAD

**Issue by cocreature** [ndmitchell/hoogle#163]
The urls for the documentation of the `ghc` package points to `https://downloads.haskell.org/~ghc/7.10.3/docs/html/libraries/ghc-7.10.3//docs/`, e.g. `https://downloads.haskell.org/~ghc/7.10.3/docs/html/libraries/ghc-7.10.3//docs/ObjLink.html#v:loadObj`. However the actual docs are at `https://downloads.haskell.org/~ghc/7.10.3/docs/html/libraries/ghc-7.10.3/ObjLink.html#v:loadObj`. The reason for this is that the docs for `ghc` and all other hackage packages are mixed and hackage packages always have the `docs` suffix so this is always appended. Not sure what the best solution is.

**Comment by ndmitchell** [comment]
A tricky problem, and one I decided to hack my way out of - if there is `~ghc` in the URL it assumes GHC style module names. Using `visibleDataCons` as an example it now works, and there is a test, and I upgraded to https and GHC 8.0.1.

**Comment by cocreature** [comment]
Thanks!
