### ISSUE TITLE
Release Hoogle 5

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#170]
Required by @chrisdone. Of benefit to @mgsloan and @snoyberg. Timeline, likely in the next 2 days or so.

**Comment by snoyberg** [comment]
Woohoo! :)

**Comment by ndmitchell** [comment]
I went to bed at 8pm last night, so no time for anything, but hopefully tonight!

**Comment by ndmitchell** [comment]
Then we accidentally Brexit'd... Done now though.

**Comment by ndmitchell** [comment]
Consider this a soft release, I hope to significantly improve it in the near future.

**Comment by chrisdone** [comment]
Great! Thanks Neil! :clap:
