### ISSUE TITLE
JSON API from the server (hoogle5)

### ISSUE THREAD

**Issue by chrisdone** [ndmitchell/hoogle#174]
Is there already a JSON API provided by hoogle5?

Now that we have `stack hoogle` working, we have easy peasy terminal-based search. We can also provide editor integration, but for automated operations, we need more detail and in a fast way that doesn't have `stack`'s overhead.

I heard talk of a JSON API which would make possible e.g. Emacs integration with a live-search, and also providing automatic imports for things out of scope and completion, cool stuff like that. I did this with hoogle in the past but the source was always sketchy. Now that stack sets up the environment for us I can finally put Hoogle to good use in tools like Intero.

**Comment by ndmitchell** [comment]
See http://hoogle.haskell.org/?hoogle=filter&mode=json as a quick example.

**Comment by chrisdone** [comment]
Perfect! Package, module, name, docs. That's all I need. I'll add intero integration soon. =3

Not sure what to do with the HTML in the results, but I can probably just strip it out with regex.

**Comment by ndmitchell** [comment]
Yep, I guarantee pretty simple HTML at most.
