### ISSUE TITLE
The `--link` parameters for the cli command doesn't seem to work

### ISSUE THREAD

**Issue by korayal** [ndmitchell/hoogle#178]
According to the `hoogle search --help` the `-l` parameter is supposed to provide URLs for each result. But the behavior  I'm getting is as below:

![image](https://cloud.githubusercontent.com/assets/313801/16762180/12fe036c-482c-11e6-9595-c12819d68c9d.png)

As you can see in the screenshot, I'm also not getting any details regarding what module a result belongs to. Am I doing something wrong? (this behavior also [seems to break](https://github.com/syl20bnr/spacemacs/issues/6551) the `helm-hoogle` module for emacs)

**Comment by ndmitchell** [comment]
Thanks for the report, fixed in HEAD and making a release as soon as my CI bots come back to me.

**Comment by korayal** [comment]
Just tried it out and it works perfectly! thank you.

**Comment by ndmitchell** [comment]
Version 5.0.1 released which fixes this bug.
