### ISSUE TITLE
Links to 'ghc' package 404

### ISSUE THREAD

**Issue by DanielG** [ndmitchell/hoogle#179]
On https://www.haskell.org/hoogle/ searching for `ModSummary +ghc` gives `http://www.haskell.org/ghc/docs/latest/html/libraries/ghc/HscTypes.html#v:ModSummary` as the first result, which 404s. `https://downloads.haskell.org/~ghc/latest/docs/html/libraries/ghc-8.0.1/HscTypes.html#v:ModSummary` works though.

**Comment by cocreature** [comment]
Use the new hoogle at http://hoogle.haskell.org, there it works correctly. I’m not sure if the old url will be updated.

**Comment by ndmitchell** [comment]
Yep, use the new one. I will update the old one to link over to the new one at some point, as tracked by https://github.com/ndmitchell/hoogle/issues/171.
