### ISSUE TITLE
Lower bounds on haskell-src-exts is no longer correct

### ISSUE THREAD

**Issue by mdorman** [ndmitchell/hoogle#187]
I think this is why the moment you went to haskell-src-exts-1.18, all your travis builds have been failing. :)

**Comment by ndmitchell** [comment]
Which lower bound? My lower bound is 1.18, which I believe to be correct. My Travis builds are working just fine. The Windows build is failing because Stack doesn't have 1.18 in it yet - this was meant to be a temporary situation, but it's dragged on for 3 months now...

**Comment by mdorman** [comment]
Doh!  You're right, I was trying to track down a nix build issue and got confused as to what I was looking at.  Sorry for the distraction.
