### ISSUE TITLE
no results for "oneShot"

### ISSUE THREAD

**Issue by andreaskern** [ndmitchell/hoogle#190]
I looked for "oneShot" and because it is used in the [foldl definition ](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.List.html#foldl)
it seems it is some kind of annotation.

Can hoogle return some kind of result for this?

**Comment by ndmitchell** [comment]
Hoogle 5 finds it: http://hoogle.haskell.org/?hoogle=oneshot

The real problem is that Hoogle 4 is still the default, and is now quite out of date. I should work on #171
