### ISSUE TITLE
Allow indexing multiple local packages

### ISSUE THREAD

**Issue by iliastsi** [ndmitchell/hoogle#192]
In Debian, we would like to be able to create a single database by indexing multiple local packages. In the past this was achieved using the `combine` command (see [update-hoogle](https://sources.debian.net/src/haskell-hoogle/4.2.43-3/debian/files_hoogle/update-hoogle/)). I don't see how this could be done in Hoogle 5.

Currently, Debian has the following [patch](https://sources.debian.net/src/haskell-hoogle/5.0.1+dfsg1-1/debian/patches/generate_from_multiple_sources/), which allows passing the `--local` flag more than once.

**Comment by ndmitchell** [comment]
Can I get that patch as a pull request? Happy to take that and make a release including it.
