### ISSUE TITLE
Can't search QuickCheck

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#208]
Visit http://hoogle.haskell.org/?scope=package%3AQuickCheck and it says "package:quickcheck-io". My guess is the CamelCase nature of QuickCheck is confusing it, given how few packages use upper case letters.

**Comment by wz1000** [comment]
I believe this should have been fixed by https://github.com/ndmitchell/hoogle/pull/216/commits/2f5e49efe8d8d31dcd613655c10e04325fc03596

**Comment by wz1000** [comment]
See http://hoogle.haskell.org/?scope=package%3AQuickCheck 

The original issue seems to be fixed, but there is some strange clipping on the page. Is this intended?

**Comment by ndmitchell** [comment]
The clipping is unrelated to this issue - it's a consequence of how the CSS works. If any CSS expert can fix it, I'd be grateful.
