### ISSUE TITLE
Add function to provide default database location to the API

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hoogle#209]
At the moment the search options are limited, and the most useful one seems to be

```haskell
withDatabase :: NFData a => FilePath -> (Database -> IO a) -> IO a 
```

Which requires the `FilePath` of the installed database.

It would be useful to have a function something like

```haskell
defaultDatabase :: IO FilePath
```

that would provide the platform-specific default database location.

**Comment by ndmitchell** [comment]
I added defaultDatabaseLocation. Can you give that a go and confirm it does what you are after? Assuming it does I'll make a release including it.

**Comment by alanz** [comment]
Without building, it looks like you have factored out the original logic for choosing the location, and exposed it.

Which is exactly what I was wanting.

Do you need more of a test?

FYI it is for use [here](https://github.com/haskell/haskell-ide-engine/pull/224), by using the API directly instead of invoking a process, with all the issues around that.

**Comment by ndmitchell** [comment]
OK, I'll make a release on that later tonight.

**Comment by ndmitchell** [comment]
hoogle-5.0.11 released.
