### ISSUE TITLE
Hoogle searching the entire DB when specified module/package is not in the DB

### ISSUE THREAD

**Issue by wz1000** [ndmitchell/hoogle#215]
$ hoogle +Garbage.Module head
    Prelude head :: [a] -> a
    Data.List head :: [a] -> a
    ...

Is it possible to change this to return no results when the specified module is not in the DB?
I need this behaviour for https://github.com/haskell/haskell-ide-engine
With the current behaviour, we often get wrong documentation/documentation for some other symbol.

**Comment by ndmitchell** [comment]
That seems entirely reasonable.

**Comment by ndmitchell** [comment]
Closed by #216.
