### ISSUE TITLE
Body only page when clicking package sometimes

### ISSUE THREAD

**Issue by FPtje** [ndmitchell/hoogle#217]
# How to reproduce

1. Open http://hoogle.haskell.org in a **NEW** tab (that step is important)
1. Type something in the search bar
1. Do **NOT** press search, the <kbd>Return</kbd> key or reload the page
1. Click some package on the left. Clicking the little `-` or `+` also works
1. Find that the link you clicked refers to `http://hoogle.haskell.org/?=<whatever>&mode=body`
1. Enjoy a Hoogle page without stylesheets

The bug seems to be in the system that loads search results *as you are typing*. After all, that's when the bug happens. As soon as you press the search button, press enter or reload the page, the `&mode=body` disappears from the links.

**Comment by ndmitchell** [comment]
Ahha! I've seen this bug before, but never managed to come up with a reproducible case, so have been unable to investigate it properly. Thanks for tracking down the cases, hopefully easy to fix it now.

**Comment by ndmitchell** [comment]
Fixed!
