### ISSUE TITLE
Signatures lacking spaces return generate no query

### ISSUE THREAD

**Issue by gabejohnson** [ndmitchell/hoogle#219]
Typing `a->b->a` into the search bar returns a list of unrelated results. I would expect the same results as `a -> b -> a` (a list of results headed by `const`).

I'm guessing delimiting on `->` or inserting spaces would fix this.

**Comment by ndmitchell** [comment]
Thanks for the report. I deliberately allow identifiers to contain `-` in them as during the lexing I might be expecting a package name. To fix that, I demand that `-` can't be the end of an identifier, so it should work now.
