### ISSUE TITLE
cabal-install package is not found

### ISSUE THREAD

**Issue by cocreature** [ndmitchell/hoogle#222]
Searching for `cabal-install` shows `cabal-install-bundle`, `cabal-install-ghc72` and `cabal-install-ghc74` but it doesn’t show the `cabal-install` package itself.

**Comment by ndmitchell** [comment]
That's because it's an executable, not a library. I agree, that should be fixed though.

**Comment by cocreature** [comment]
> That's because it's an executable, not a library.

I’m a bit confused by this. `cabal-install-bundle` is also only an [executable](https://hackage.haskell.org/package/cabal-install-bundle-1.18.0.2.1/src/cabal-install-bundle.cabal) but that does show up.

**Comment by ndmitchell** [comment]
Good point. Now I'm thoroughly confused.

**Comment by ndmitchell** [comment]
Also missing for weeder, which I wrote so I nothing has nothing "funky" in it.

**Comment by ndmitchell** [comment]
Turns out that any package which was an executable in Stackage wouldn't show up in the list - which includes weeder and cabal-install. I've now fixed that code - just redeploying Hoogle now. Thanks for the report!
