### ISSUE TITLE
Problems with comments.

### ISSUE THREAD

**Issue by AnthonyJacob** [ndmitchell/hoogle#225]
Some comments cause parse errors: `-- *`, `-- |=`, `{- | -}`.

If any of these are anywhere in my file, running `stack hoogle` will throw a parsing error!

**Comment by ndmitchell** [comment]
These are really bugs/restrictions of Haddock, and if you just do `stack haddock` (which generates the documentation for your package) you get the same issues. I strongly recommend fixing them, as if you don't, your package won't have documentation when you upload it to Stackage.
