### ISSUE TITLE
gtk2hs homepage very dead

### ISSUE THREAD

**Issue by gbaz** [ndmitchell/hoogle#237]
As it was a wordpress blog on the very unmaintained projects.haskell.org it has been largely dead since forever. But now that we've end-of-lifed that blog it is extra-dead, and what remains is a redirect to the archives.haskell.org site, which, since it does not run the mysql database etc, just gives a bare useless directory listing.

A new homepage might be in order, but in the meantime the existing one should probably be removed? (I think that cabal revisions can fix this up on hackage as well as in the current source...)

**Comment by gbaz** [comment]
Whoa, sorry, ticket in completely wrong repo!  Please delete :-/

**Comment by ndmitchell** [comment]
Lol. No need to delete and I don't even know how!
