### ISSUE TITLE
hoogle data can't fetch data

### ISSUE THREAD

**Issue by bixuanzju** [ndmitchell/hoogle#24]
Below is when I ran ``hoogle data`` in command line
>
~  hoogle data
--2013-08-09 20:23:36--  http://code.galois.com/darcs/haskell-platform/haskell-platform.cabal
Resolving code.galois.com... 66.193.37.216
Connecting to code.galois.com|66.193.37.216|:80... failed: Connection refused.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
hoogle: Failed to download http://code.galois.com/darcs/haskell-platform/haskell-platform.cabal

Also I pinged 66.193.37.216, no package received.

PS: no problem with my internet connection

**Comment by ndmitchell** [comment]
Every server has moved several times since the above reports, so I'm going to assume the new server locations, plus new HTTP libraries have fixed it in the dev version.

**Comment by bixuanzju** [comment]
I think it can close now. Thanks for your efforts.

**Comment by filib** [comment]
@ndmitchell I've also been having trouble fetching from `code.galois.com` for the last few days.

```
% hoogle --version                                                                                                                                                            1 ↵
Hoogle v4.2.41, (C) Neil Mitchell 2004-2012
http://haskell.org/hoogle
% hoogle data
Downloading downloads/platform.cabal
WARNING: Could not find command line program wget.
# platform.cabal (for downloads/platform.cabal)
curl: (7) Failed to connect to code.galois.com port 80: Operation timed out
hoogle: Error when running Shake build system:
* default.hoo
* platform.hoo
* platform.txt
* downloads/platform.cabal.cache
* downloads/platform.cabal
user error (Development.Shake.command, system command failed
Command: curl -sSL http://code.galois.com/darcs/haskell-platform/haskell-platform.cabal --output downloads/platform.cabal
Exit code: 7
Stderr:
curl: (7) Failed to connect to code.galois.com port 80: Operation timed out
)
```

What's the best way to work around this? Can I download from elsewhere manually? Is this something I could help document somewhere?

**Comment by ndmitchell** [comment]
@filib the best thing to do is probably wait a further 24 hours - given Galois is a company, it's likely something has fallen over and they haven't noticed because its the weekend. If it persists after that I'll reach out to them.

With the dev version of Hoogle it doesn't use galois links at all, but that's not been released and isn't really working.

**Comment by ndmitchell** [comment]
I am now using the patch in https://github.com/ndmitchell/hoogle/issues/24#issuecomment-38986800 - @filib - can you confirm it now works with version 4.2.42?

**Comment by filib** [comment]
@ndmitchell sorry for the late reply, managed to catch the dreaded lurgy at the Haskell Exchange.

4.2.42 works a treat and it also looks like Galois have gave their server a boot as 4.2.41 also works fine.

**Comment by ndmitchell** [comment]
Thanks for the update 1 hope you have recovered now.
