### ISSUE TITLE
Inconsistent rendering of type signatures

### ISSUE THREAD

**Issue by Lysxia** [ndmitchell/hoogle#251]
Here are three results for `withExceptT` which seem to have the same source but all of them have type signatures with distinct parenthesizations, one incorrect.

https://hoogle.haskell.org/?hoogle=withExceptT

![sc-2018-05-03t07 20 46-04 00](https://user-images.githubusercontent.com/2515201/39573778-96556826-4ea2-11e8-83e5-f92f8e2169d5.png)

**Comment by ndmitchell** [comment]
Haddock provides the type signatures, and previous versions of Haddock were a bit buggy. Looking at the incorrect line, it's also present in https://hackage.haskell.org/package/mtl-2.2.2/docs/mtl.txt - so doesn't seem like a bug Hoogle can do much about. I suggest the only thing I can do is make sure transformers comes before mtl in the ranking, at least then the first answer will be correct.

**Comment by ndmitchell** [comment]
I added a nasty hack that puts transformers above mtl so from tomorrow evening it will have at least a correct answer first. I don't think there's much to do until mtl re-uploads correct docs.
