### ISSUE TITLE
A way of getting XML free JSON from the JSON API

### ISSUE THREAD

**Issue by DavidM-D** [ndmitchell/hoogle#254]
Currently if I query the JSON API I get results back  that look like this
`"item": "<span class=name><0>dbg2</0></span> :: Show a =&gt; String -&gt; a -&gt; a",`
when I'd much rather it looked like
`"item": "dbg2 :: Show a => String -> a -> a"`
Do you mind if I add a query parameter to enable this type of behaviour?

**Comment by ndmitchell** [comment]
What language/environment are you consuming the output in? It should be pretty easy to remove the tags and escapes in most, but if not, I wouldn't mind too much - but it wouldn't be my first preference.

**Comment by DavidM-D** [comment]
Yea, that's a fair point, I guess looking at a couple of the 
hoogle editor plugins generally they're not interested in any of 
the XML stuff. I'll just do it on the elisp side then.
