### ISSUE TITLE
Doesn't find Data.Functor.(<&>), the `flip fmap`

### ISSUE THREAD

**Issue by ulidtko** [ndmitchell/hoogle#258]
Steps to reproduce:

1. Go to https://www.haskell.org/hoogle
2. Punch in the type signature `Functor f => f a -> (a -> b) -> f b`

So, perhaps obviously, I'm trying to dig up the spelling of the operator [`(<&>)`][flip fmap] from `base` by hoogling the signature I know it should have.

Somehow though, it's nowhere near the first page of results. How come?..

[flip fmap]: http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Functor.html#v:-60--38--62-

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/hoogle/blob/master/README.md#hoogle-4-vs-hoogle-5 - basically `<&>` got added after the Hoogle 4 search engine, but it's in Hoogle 5 at https://hoogle.haskell.org/?hoogle=Functor%20f%20%3D%3E%20f%20a%20-%3E%20(a%20-%3E%20b)%20-%3E%20f%20b (although not as high as I would have hoped).

**Comment by ulidtko** [comment]
Ah, yes, that makes sense. I think I'd even stumbled over this before. Will try to remember to go to https://hoogle.haskell.org instead of https://haskell.org/hoogle !
