### ISSUE TITLE
Hoogle doesn't find pattern synonyms in Data.Sequence

### ISSUE THREAD

**Issue by ttuegel** [ndmitchell/hoogle#261]
Hoogle doesn't seem to find the pattern synonyms bundled with [`Data.Sequence.Seq`](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Sequence.html#t:Seq): https://hoogle.haskell.org/?hoogle=%3A%3C%7C

**Comment by flip111** [comment]
Seems to be fixed upstream now. And hoogle gives results. Perhaps close ticket?

**Comment by ndmitchell** [comment]
@flip111 not sure what you mean - I can't see it fixed upstream and don't see results in Hoogle...

**Comment by flip111** [comment]
https://github.com/haskell/haddock/issues/946 lists https://github.com/haskell/haddock/pull/947 as fix i believe

When i click the link https://hoogle.haskell.org/?hoogle=%3A%3C%7C in comment https://github.com/ndmitchell/hoogle/issues/261#issue-365164093 i see 4 search results

```
type (:<|) f x = A f x
Uses
opaleye Opaleye.Internal.TypeFamilies
data a :<|> b
Uses
servant Servant.API Servant.API.Alternative
Union of two APIs, first takes precedence in case of overlap. Example:

>>> :{
type MyApi = "books" :> Get '[JSON] [Book] -- GET /books
:<|> "books" :> ReqBody '[JSON] Book :> Post '[JSON] () -- POST /books
:}

(:<|>) :: a -> b -> (:<|>) a b
Uses
servant Servant.API Servant.API.Alternative, servant-js Servant.JS.Internal
data (:<|>) a b
Uses
servant-js Servant.JS.Internal
Union of two APIs, first takes precedence in case of overlap. Example:

>>> :{
type MyApi = "books" :> Get '[JSON] [Book] -- GET /books
:<|> "books" :> ReqBody '[JSON] Book :> Post '[JSON] () -- POST /books
:}
```

**Comment by flip111** [comment]
Ah sorry i see what you mean, 
[`Data.Sequence.Seq`](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Sequence.html#t:Seq) is not one of the results. However upstream fix is there, no ?

**Comment by ndmitchell** [comment]
Yeah, I guess it's just waiting for containers to regenerate their docs, perhaps on a new release. I guess however the fundamental issue is fixed, so it is now a containers problem. Thanks for noticing!

**Comment by expipiplus1** [comment]
I think that this might still be broken on Hoogle's side.

To reproduce:

Compile a package with these contents:

- `package.yaml`
```yaml
name: hoogle-test
dependencies:
  - base
library:
  source-dirs: .
```
- `MyModule.hs`
```haskell
{-# LANGUAGE PatternSynonyms #-}
module MyModule
  ( pattern MyPattern
  ) where

pattern MyPattern :: ()
pattern MyPattern = ()
```

- Observe that the pattern synonym is present in the generated documentation file `hoogle-test.txt`

```
-- Hoogle documentation, generated by Haddock
-- See Hoogle, http://www.haskell.org/hoogle/


@package hoogle-test
@version 0.0.0

module MyModule
pattern MyPattern :: ()
```

- Observe that Hoogle can find `MyModule`
```
$ hoogle MyModule
module MyModule
```

- Observe that Hoogle can not find `MyPattern`

```
$ hoogle MyPattern
No results found
```

**Comment by expipiplus1** [comment]
oh, and a `.warn` file is generated with this content `hoogle-test:9:failed to parse: pattern MyPattern :: ()`
