### ISSUE TITLE
Turn todo3.txt into a test suite

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#265]

**Comment by matt-noonan** [comment]
What is the best way to run tests like "ensure the first hit for `(a -> b) -> Maybe a -> Maybe b` is `fmap`? Can we assume that the db from `hoogle generate` is available during tests?

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/hoogle/blob/master/src/Action/Search.hs#L152-L153 - yes - you can assume the database is available.

Probably add a new helper like `===~` for in the top-5, or an actual function `top 5` to add new types of search.
