### ISSUE TITLE
json output from the command line app

### ISSUE THREAD

**Issue by meck** [ndmitchell/hoogle#272]
I was tinkering about (see #271) and wanted to use the library for querying local databases, but since its strict about versions, it seems a bit of a hassle to use it that way. It would be nice to have a ```--format=json``` or parameter similar to use a locally installed cli version of Hoogle, like the web version?

**Comment by ndmitchell** [comment]
That seems a plausible way to go for version interoperability, although I'd be tempted to just require a specific version of the Hoogle library and call the generator as needed - the format doesn't change that often and tightly coupling is usually less effort. However, the feature seems reasonable, so up to you and patch welcome.

**Comment by meck** [comment]
I went with keeping a separate database, all good. Closing this
