### ISSUE TITLE
JSON output from command line

### ISSUE THREAD

**Issue by taktoa** [ndmitchell/hoogle#287]
For many applications (e.g.: editor integration) it would be quite useful if we could have a machine-readable JSON output from the `hoogle` command line. It shouldn't be too hard, and it would prevent people from writing ad-hoc parsing code for the output of `hoogle`. It would also be nice if the output from `hoogle search -i --link` (i.e.: the package name and URL) could be included in this JSON output. I'm thinking something like this:

```
$ hoogle search --json Just
[
    {
        "package": "Cabal",
        "module": "Distribution.Compat.Prelude.Internal",
        "identifier": "Just",
        "type": "a -> Maybe a",
        "url": "file:///nix/store/izd6sl5dvgxijzdxcg1zw77q61k7jn3l-ghc-8.4.3-doc/share/doc/ghc/html/libraries/Cabal-2.2.0.1/Distribution-Compat-Prelude-Internal.html#v:Just"
    },
    {
        "package": "accelerate",
        "module": "Data.Array.Accelerate.Data.Maybe",
        "identifier": "Just",
        "type": "a -> Maybe a",
        "url": "file:///nix/store/gzj1q15695brh95dsjdxpj8s33rc17sq-accelerate-1.2.0.0-doc/share/doc/html/Data-Array-Accelerate-Data-Maybe.html#v:Just"
    },
    ...
]
```

**Comment by taktoa** [comment]
Potentially also useful: the syntax tree for the type, so that editors could easily syntax-highlight it.

**Comment by ndmitchell** [comment]
Nothing available at the moment, but given that you can generate JSON via the web API (e.g. https://hoogle.haskell.org/?hoogle=Just&mode=json) all the pieces are there. I'd welcome a PR as you describe. Note that the existing JSON already contains formatting information about types, enough for the editor syntax highlighting you are after.

**Comment by iAmMrinal0** [comment]
I'd like to take this up.
Should I add the count based approach for JSON output too? I'd prefer it if I get all the outputs in a single go.

**Comment by ndmitchell** [comment]
@iAmMrinal0 you fixed it too fast for me to answer :)
