### ISSUE TITLE
Prefer `fail` over `error` in IO

### ISSUE THREAD

**Issue by fendor** [ndmitchell/hoogle#292]
The function `fail` is well-defined for IO code while `error` isn't.
Moreover, it makes you think, what will happen and what do you have to do to make sure the exception will be thrown at the expected moment, in order to catch it.

Are you interested in a PR that replaces all occurrences of `error` in IO code with `fail`?

**Comment by ndmitchell** [comment]
I am. I'd also be happy with `errorIO` instead - but not too fussed (`fail` doesn't always mean throw an error, whereas `errorIO` does). https://hackage.haskell.org/package/extra-1.6.14/docs/Control-Exception-Extra.html#v:errorIO

**Comment by fendor** [comment]
However, it feels a little bit more unexpected to catch ErrorCall instead of IOException, especially in the face of IO related errors, such as, the database is garbage.
