### ISSUE TITLE
request for hackage revision: hoogle-5.0.17.1 should require network<3

### ISSUE THREAD

**Issue by int-e** [ndmitchell/hoogle#296]
This would allow building hoogle with ghc-7.10.3 (ancient, I know). Currently, `cabal install hoogle` finds an installation plan involving `hoogle-5.0.17.1` (newer versions are ruled out via `conduit-1.3`) and `network-3.1.0.0`, but in the end, hoogle fails to be built:

```
Building library for hoogle-5.0.17.1..

src/Input/Download.hs:15:8:
    Could not find module ‘Network’
    Use -v to see a list of the files searched for.
```

Building with '--constraint network<3` succeeds.

Could you please add this constraint for `hoogle-5.0.17.1` on hackage  by making a new revision there?

**Comment by ndmitchell** [comment]
Done as requested - let me know if I screwed it up!
