### ISSUE TITLE
"Uses" for packages should link to reverse package dependencies instead of "Aelve Codesearch"

### ISSUE THREAD

**Issue by adamse** [ndmitchell/hoogle#297]
For example

![image](https://user-images.githubusercontent.com/75746/57082271-51afc200-6cee-11e9-89b0-3fdb4b363aa5.png)

Might be better linked to https://packdeps.haskellers.com/reverse/th-abstraction instead of https://codesearch.aelve.com/haskell/search?query=th-abstraction&filter=&precise=on

**Comment by ndmitchell** [comment]
Excellent idea! Just implemented and pushed, will be live later tonight.
