### ISSUE TITLE
Bad URL trying to access package on Hoogle with --local

### ISSUE THREAD

**Issue by iAmMrinal0** [ndmitchell/hoogle#314]
Error log:
```
Bad URL: /file/nix/store/2li66qs0v2l9z8wds8cjfclik0gnkbi8-aeson-1.4.2.0-doc/share/doc/aeson-1.4.2.0/html/
CallStack (from HasCallStack):
  error, called at src/General/Web.hs:161:30 in hoogle-5.0.17.9-8KC9bAoFJjQ2tgrzbv1WR:General.Web
```

I've figured out where the issue is and will send a PR for the same.

**Comment by iAmMrinal0** [comment]
Closing this as I found the actual root cause of the issue and will send a new PR. Apologies for this.

**Comment by ndmitchell** [comment]
Thanks for your fixes - I'll make a release with this change over the weekend!
