### ISSUE TITLE
doesn't handle unicode searches

### ISSUE THREAD

**Issue by obfusk** [ndmitchell/hoogle#324]
Try e.g. https://hoogle.haskell.org/?hoogle=≠

It seems to split unicode characters into separate bytes somewhere along the way.

Unicode results are fine: https://hoogle.haskell.org/?hoogle=package%3Abase-unicode-symbols+Eq+a+%3D%3E+a+-%3E+a+-%3E+Bool

**Comment by obfusk** [comment]
I'd be happy to look into fixing this, but I'm not that familiar with the codebase so I'm not sure where to start looking.

**Comment by ndmitchell** [comment]
Agreed it's a bug, but also no idea where this is happening. Any PR or investigation most welcome!
