### ISSUE TITLE
Hoogle can't restrict number of output lines with cmdline --json flag

### ISSUE THREAD

**Issue by monkoose** [ndmitchell/hoogle#331]
Hello, i have a question.
Any possible way to restrict number of generated json items from cmdline tool with `--json` flag, like with `--count` for default output?
If no, is it planned for future releases?

**Comment by ndmitchell** [comment]
I believe count flag does it. Did you find it?

**Comment by monkoose** [comment]
I found workaround for my needs. But `count` doesn't work and you get all possible output with `--json` flag, and for some query it could be big like 10,000+ items.

**Comment by ndmitchell** [comment]
Sounds like a legitimate issue. Very happy to take a patch.

**Comment by monkoose** [comment]
I don't have one. Waiting for implementation.

**Comment by ndmitchell** [comment]
Pushed a fix. Can you test it from master and confirm it works the way you were hoping? If so, I'll make a release.

**Comment by monkoose** [comment]
Currently not near my PC. Give me ~ 1 day.

**Comment by monkoose** [comment]
Tested.

**Comment by ndmitchell** [comment]
Thanks, released as v5.0.17.13
