### ISSUE TITLE
Accepting google search "q=??" query?

### ISSUE THREAD

**Issue by hackle** [ndmitchell/hoogle#332]
I got this nice result from google search

![image](https://user-images.githubusercontent.com/3759593/68795698-5b12e180-06b6-11ea-8ae4-b26f5103cee1.png)

but if I click through I ended up on a landing page, not the "flip" entry.

![image](https://user-images.githubusercontent.com/3759593/68795791-885f8f80-06b6-11ea-85e1-b42dc780eda3.png)

Would be nice to fix this one?

**Comment by ndmitchell** [comment]
Yep, a while back Hoogle used to use `q`, and I guess those links made it into the Google cache. Now I prefer `?hoogle=` (since otherwise it confuses autocomplete), but I've just made it accept either. Thanks for the idea!
