### ISSUE TITLE
Aelve Codesearch is shutting down on Dec 15th

### ISSUE THREAD

**Issue by neongreen** [ndmitchell/hoogle#333]
Hey! I'm planning to shut down Codesearch. So, `Uses` should be redirected or disabled.

**Comment by ndmitchell** [comment]
Sorry to hear that! They're gone now.

**Comment by adamse** [comment]
The uses link for packages (linking to https://packdeps.haskellers.com/reverse) is still useful.

**Comment by ndmitchell** [comment]
Good idea - I've put them back.
