### ISSUE TITLE
Please support haskell-src-exts 1.23.x

### ISSUE THREAD

**Issue by peti** [ndmitchell/hoogle#334]
A new version of `haskell-src-exts` has come out that is currently excluded by Hoogle's version range. I tried the build ignoring the upper bound and it succeeded nicely, so I assume that all there is to it is to edit the Hoogle cabal file on Hackage.

**Comment by ndmitchell** [comment]
Currently on holiday but planning to do it when I get back (end of the week or so).

**Comment by ndmitchell** [comment]
Released 5.0.17.14 which supports the new version.
