### ISSUE TITLE
Have an option to remove HTML formatting on web API

### ISSUE THREAD

**Issue by GCrispino** [ndmitchell/hoogle#337]
Taking as example the result for the URL `https://hoogle.haskell.org/?mode=json&hoogle=map&start=1&count=1`:
```json
[
  {
    "url": "https://hackage.haskell.org/package/base/docs/Prelude.html#v:map",
    "module": {
      "url": "https://hackage.haskell.org/package/base/docs/Prelude.html",
      "name": "Prelude"
    },
    "package": {
      "url": "https://hackage.haskell.org/package/base",
      "name": "base"
    },
    "item": "<span class=name><s0>map</s0></span> :: (a -&gt; b) -&gt; [a] -&gt; [b]",
    "type": "",
    "docs": "<a>map</a> <tt>f xs</tt> is the list obtained by applying <tt>f</tt>\nto each element of <tt>xs</tt>, i.e.,\n\n<pre>\nmap f [x1, x2, ..., xn] == [f x1, f x2, ..., f xn]\nmap f [x1, x2, ...] == [f x1, f x2, ...]\n</pre>\n"
  }
]
```

The `item` and `docs` values contain HTML text. Wouldn't be nice if there was an option to get only plain text in these responses (in case it does not exist yet)? For the case that a client does not support HTML parsing (command line app, mobile, etc).

In case it does exist, I couldn't find this option anywhere.

**Comment by ndmitchell** [comment]
There is no option, but I'd be happy to get a patch adding one. I think there is already a function for stripping the HTML easily.

**Comment by GCrispino** [comment]
I'd be happy to help, but I'd never contributed in a Haskell project before. Maybe I could do it if someone pointed me through potential points of change in the code.

**Comment by ndmitchell** [comment]
Sounds great! The code that serves up JSON is at https://github.com/ndmitchell/hoogle/blob/master/src/Action/Server.hs#L111-L118. I would imagine that you also `lookup "format" inputArgs == Just "text"` (or maybe it wants to be mode=json-text? I'm not fussed). Once you have that, for each value in `results` you have a `Target`. Change the `targetItem` and `targetDocs` from being HTML in a String, to plain text in a String, with the `unHTML` function in `General.Util`.

**Comment by GCrispino** [comment]
Awesome! I've already started working on this and soon I'll open a PR for this. Thanks!

**Comment by GCrispino** [comment]
Closing this as https://github.com/ndmitchell/hoogle/pull/338 solved it.
