### ISSUE TITLE
Cannot install hoogle using cabal 3.0.0.0

### ISSUE THREAD

**Issue by maxild** [ndmitchell/hoogle#344]
Hi,

I have tried to install `hoogle` with cabal 3.0.0.0. 

I got the following [output](https://gist.github.com/maxild/53475f6bed412d1eae5d9d552803d09e)

The log file contains

```
Configuring library for zlib-0.6.2.1..
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing (or bad) C library: z
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

I am new to cabal. I am guessing

```
cabal install zlib-0.6.2.1 --lib # or cabal v2-install zlib-0.6.2.1 --lib (?)
```

is the problem. Maybe this issue should be filed in `zlib` project?

Please help.

**Comment by ndmitchell** [comment]
Yep, please raised this with the zlib project. Happily, they are also the people behind Cabal :)

If you are on linux an `apt-get zlib` or similar might help.

**Comment by maxild** [comment]
Can i hijack this issue before closing it with a question regarding tools setup in Haskell ?

https://github.com/ndmitchell/ghcid/issues/307 

I don't really need cabal or stack, but I need to install tools to get nice editor experience (ghcid, hlint, hoogle and brittany), and therefore I am a bit confused as stated in the question.

BTW ghci is probably the best REPL I have ever experienced, and your tools (ghcid especially, but also hlint) are remarkable good:smile:

**Comment by ndmitchell** [comment]
Thanks! I've answered over on that ticket, so I'll close this one.
