### ISSUE TITLE
Exact match on "module:" name

### ISSUE THREAD

**Issue by runeksvendsen** [ndmitchell/hoogle#345]
Say I perform a search `f module:Data.Functor -is:package`. Is it possible to make Hoogle return only results from the `Data.Functor` module, and not from other modules that *start with* `Data.Functor` (like `Data.Functor.Rep`, `Data.Functor.Day.Curried`, `Data.Functor.Kan.Lan` etc.) --  ie. an exact match on the module name?

**Comment by ndmitchell** [comment]
No idea. Perhaps `Data.Functor.` with the trailing dot? But I didn't write the exact feature, so I'm not that familiar with it.

**Comment by runeksvendsen** [comment]
As far as I can see, the `is:exact` option is the only way to do an exact match and it does not apply to the `module:` part of the query.
