### ISSUE TITLE
hoogle: hseToItem failed

### ISSUE THREAD

**Issue by erikd** [ndmitchell/hoogle#355]
After generating hoogle files using:
```
cabal haddock all --haddock-hoogle
```
and then running:
```
hoogle generate --local=.
```
I get:
```
hoogle: hseToItem failed, match (AggregatedMessage as) (ExtractAggregation n) op t = matchThreshold op t $ extractAggregation n as
CallStack (from HasCallStack):
  error, called at src/Input/Haddock.hs:79:47 in hoogle-5.0.17.15-inplace:Input.Haddock
```

**Comment by ndmitchell** [comment]
That suggests: `match (AggregatedMessage as) (ExtractAggregation n) op t = matchThreshold op t $ extractAggregation n as` made it into your Hoogle database. That should not be. But generally, new version of Haddock regress in new ways, so I guess I should ignore this as expected :(

**Comment by erikd** [comment]
This is haddock from ghc-8.6.5. Rather than a bug in haddock could this be a bug in our Haddock markup?

**Comment by ndmitchell** [comment]
No, the markup gets escaped and processed differently. Can you take a look at your Hoogle output files (from `--haddock-hoogle`) to see if you can find that line? It should be in a .txt file somewhere. That should give a clue as to what ends up in the Haddock output and where things went wrong.

**Comment by erikd** [comment]
How does hoogle decide which `*.txt` files to process? The one that caused the problem actually does seem to be generated documentation that ended up in `dist-newstyle/` .

Deleting that one file and it suceeds. Closing this.

**Comment by ndmitchell** [comment]
With `--local=.` it just walks that directory looking for `.txt` files. Not the most robust... So that explains what was happening, maybe `.txt` wasn't the best filename extension, but I think we're stuck with it now. Thanks for tracking it down!
