### ISSUE TITLE
How to generate hoogle database for local cabal package including dependencies?

### ISSUE THREAD

**Issue by noughtmare** [ndmitchell/hoogle#361]
This was just asked on the Monthly Hask Anything on reddit: https://old.reddit.com/r/haskell/comments/jllzfa/monthly_hask_anything_november_2020/gbc5myb/

**Comment by kokobd** [comment]
Is this issue resolved?

**Comment by noughtmare** [comment]
I guess we need to use https://hackage.haskell.org/package/cabal-hoogle
