### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by unit73e** [ndmitchell/hoogle#378]
Not exactly an issue but is it possible to have static releases instead of just tags?

**Comment by ndmitchell** [comment]
What do you mean by static releases - actual binaries? What's the use case for that? Most people don't need to build hoogle binaries at all and can just use it from the web, but if you do want to run a custom hoogle, you probably also want to compile your documentation too, at which point building Hoogle isn't a big deal.

**Comment by unit73e** [comment]
@ndmitchell yes I mean actual binaries. It's useful to have hoogle locally to get documentation in the text editor itself. Language server clients are doing that nowadays, kind of like IDEs do. A binary would be useful to avoid compilation. My use case is very specific because in Arch Linux in AUR we have binaries and non-binaries and right now the static hoogle package is non-binary, so we have to compile it all the time. So to sum up it would be a centralized easier way to get hoogle instead of each distro having to compile it.

**Comment by ndmitchell** [comment]
Don't most distros compile these things themselves with their preferred options/GHC versions etc? I'm not sure how widely useful this is. I think the rough approach would be to do https://github.com/ndmitchell/hlint/blob/master/.github/workflows/release.yml for Hoogle, but I'm slightly wary as I know these release-only jobs often break, are pretty fragile, and have been a fairly high cost.

**Comment by unit73e** [comment]
@ndmitchell yes. Arch Linux Haskell packages are somewhat "broken" though because it has a philosophy everything must be dynamically linked and Haskell seems to be in favor of static packages for reasons I haven't investigated much yet. I tend to agree with the Arch Linux way because it encourages fixing backwards compatibility, while fixed versions encourage not fixing backwards compatibility, but that's just my opinion.

If you guys feel it's too high cost for little profit that's fine by me. It's just a nice to have. It's not like having releases only on github is perfect anyway, because that would mean depending on github.

**Comment by ndmitchell** [comment]
Unfortunately I think the answer is it's too high cost for too little benefit - sorry!

**Comment by unit73e** [comment]
No problem. The current way isn't too bad.
