### ISSUE TITLE
`hoogle generate` times out

### ISSUE THREAD

**Issue by RobWalt** [ndmitchell/hoogle#408]
I'm on NixOS and I'm getting

```
Starting generate
Downloading https://raw.githubusercontent.com/haskell/haskell-platform/master/hptool/src/Releases2015.hs... hoogle: HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/haskell/haskell-platform/master/hptool/src/Releases2015.hs"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 ConnectionTimeout
```

when trying to run `hoogle generate`

**Comment by ndmitchell** [comment]
If you try and fetch https://raw.githubusercontent.com/haskell/haskell-platform/master/hptool/src/Releases2015.hs with curl or similar does it work for you? It looks like you are going through a proxy?

**Comment by RobWalt** [comment]
Just had another try and it looks like it works now. Seems to be NixOS related since I updated my system today to track a more recent version of the package repository.

Sorry for the trouble 🙈 

For anyone facing the same issue: It's fixed by updating to a pinned version of the `nixos-23.05` branch with a hash that is older than the date 24.06.
