### ISSUE TITLE
Should have option to depend on crypton-x509

### ISSUE THREAD

**Issue by ysangkok** [ndmitchell/hoogle#409]
The x509 package has been forked to crypton-x509 and many packages are already depending on it.

It would be nice if hoogle also worked with crypton-x509 instead.

**Comment by ndmitchell** [comment]
#406 changes to crypton-connection. Is that sufficient? Or is something more required?

**Comment by ysangkok** [comment]
Oh, sorry, I had only checked hackage! I just downloaded from git and it works perfectly with crypton! Sorry for the noise.
