### ISSUE TITLE
release new hoogle to hackage

### ISSUE THREAD

**Issue by gbaz** [ndmitchell/hoogle#410]
Because of the issues with the forked crypto ecosystem, the current hoogle version on hackage is nigh-unbuildable. A new release soon, which incorporates the fixes already merged into this repo, would be very welcome

**Comment by danse** [comment]
I think i stumbled upon this, http-conduit-2.3.8.2 and warp-tls-3.3.6 fail the build. Related issues: https://github.com/yesodweb/wai/issues/936, https://github.com/snoyberg/http-client/issues/511

**Comment by locallycompact** [comment]
Bumping this. We need a release compatible with crypton-connection.

**Comment by ndmitchell** [comment]
Just made 5.0.18.4 - sorry for the delay
