### ISSUE TITLE
Problems after building with crypton-connection-0.4.0

### ISSUE THREAD

**Issue by UnrelatedMicrowave** [ndmitchell/hoogle#423]
After installing hoogle with `cabal install` the command `hoogle generate` was giving the error below:
`
Starting generate
Downloading https://www.stackage.org/lts/cabal.config... hoogle: src/Input/Download.hs:(45,8)-(49,7): Missing field in record construction settingClientSupported
`
Because the `TLSSettings` constructor takes more than those 3 arguments with this version of the library.

I solved the problem by changing the `hoogle.cabal` file, I've put a `== 0.3.2` after the `crypton-connection` dependency.

Sorry if this issue isn't well written, first time writing one.

Information that maybe is useful:
`cabal --version` gives:
`
cabal-install version 3.10.3.0
compiled using version 3.10.3.0 of the Cabal library 
`
and `ghc --version` gives:
`The Glorious Glasgow Haskell Compilation System, version 9.4.8`

**Comment by rmullin7286** [comment]
I can confirm that this issue is also affecting me after a fresh install of hoogle

**Comment by evan0greenup** [comment]
@UnrelatedMicrowave , I believe the simplest solution is add `stack.yaml` and built with stack.

The latest `crypton-connection` on Stackage is `0.3.2`. Which will make it works.

<https://github.com/ndmitchell/hoogle/issues/427>

**Comment by ndmitchell** [comment]
Moved to support crypto-connection 0.4.1 in the repo, and add a == 0.3.2 in a Hackage revision. Let me know if you still see issues.
