### ISSUE TITLE
Don't assume http, generate protocol-relative URIs

### ISSUE THREAD

**Issue by redneb** [ndmitchell/hoogle#56]
Currently, both hoogle and hackage are available via https. One issue is that when I use the https version of hoogle to search for something, it returns results from the http version of hackage. This can be fixed very easily; instead of producing URIs of the form

    http://hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html#v:map

it should produce a "protocol-relative URI":

    //hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html#v:map

**Comment by hdgarrood** [comment]
Since Hackage allows HTTPS, why not just always link to the HTTPS version?

**Comment by ndmitchell** [comment]
I remember those crazy days in early 2014 when the idea of accessing your Haskell documentation via https just seemed like overkill. Of course, given the intervening year, everything should be https only where available.

**Comment by ndmitchell** [comment]
Done, I also followed all redirects on the pages I was linking too.
