### ISSUE TITLE
Please ship original (non-minified) jquery sources

### ISSUE THREAD

**Issue by iustin** [ndmitchell/hoogle#77]
This creates a problem for the Debian packaging, as the minified sources are not considered the "preferred form of modification". We workaround it by shipping ourselves the original sources, but it would be better if the upstream archive already contains it.

**Comment by ndmitchell** [comment]
Fixed in the next version (which is currently at https://github.com/ndmitchell/hogle) by using the `js-jquery` package on Hackage, which ships the sources properly. All other jQuery addins are shipped unminified.
