### ISSUE TITLE
Add a cabal flag to minimise dependencies

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hoogle#98]
Should be possible to build a version of Hoogle which doesn't support `server` mode and uses less dependencies. A Cabal flag is probably the best way to do that.

**Comment by nomeata** [comment]
This might also be interesting for distributions packaging `hoogle`.

**Comment by ndmitchell** [comment]
@nomeata, how come? Until you wrote that comment, I was tending towards declaring it not worth fixing. The main hassle was for windows users due to the network dependency, but MinGHC solves that.

**Comment by nomeata** [comment]
I didn’t have a close look (sorry) but less dependencies are always good. Might actually be a non-problem.

**Comment by ndmitchell** [comment]
I'll consider this a non-issue until someone runs into concrete problems with it.
